language: node_js
node_js:
- '6'
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
env:
  global:
    secure: mkKDMgubeD7ci7un+wWGhVN/JoAVDJMBJGPuhrW2T0VpdpxzbymX5Ec/G2hZAMwFlFkbIWd1sIq+WwB8SoBXxZgOYKQp4AacgXAh3DTdbfFXcd4p7E7ZmTUozEGBmahtU32lzr+7Q5L5fZ7220SAPzVmiVg11ztLQe9yv6/a/adW/A+ejGJ2ccKbAClY40KGPNQwLolHT9QhRXW7p6DND+T7/7jQfAbJ3utG4jSS7aP2zYnwvpLFYxftmlZNo+6uw/AtYVLa9cVSLZsBAmOXHouMaTjsCKt5xdmn1Zm4RA+h9lnsBD9MbUxJlyBCiPrm9zSX5OUM0anPBxCcKzw8N6SeqDqUxqX3ZB2kCrQzWNQLHvRhOtey5YYHQRO0ko9mXycWoP5zQZJa5tvG7ZCxRHRxJD097Ble0Us9YgtRnOUd2kIy9MbL/JwuDFqxAq4eJbzPfJD5o+iIm420q1JcJ9NOVufSbHRrO7gNKj24fTsRP8Vkzfl7lveYskBeZQrGqrfivfO8H6uMbveM0ZiznQF2rGeriv5CYzdLvUUhOea71KRNKEh8bnUPYWIxr5/w3ohuqU/bhtaoVQA3VSQVY3IOGwwlnsKQMfycQFAMD9JrypAFaskAYXyeXxcwq4RtLSSSs8gYmfnUgWhl7yhYfSsdz0GRLe6OBp23cdHpgrI=
